version: "2"

run:
  go: "1.24.1"
  concurrency: 10
  allow-parallel-runners: true
  timeout: 15s
  tests: true
  build-tags:
  - darwin
  - integration
  relative-path-mode: gomod

linters:
  enable:
  - bodyclose
  - contextcheck
  - cyclop
  - dupl
  - durationcheck
  - dupl
  - errcheck
  - errname
  - gocritic
  - gocognit
  - gocyclo
  - gochecksumtype
  - godot
  - gosec
  - govet
  - ineffassign
  - lll
  - misspell
  - mnd
  - nakedret
  - nilerr
  - nilnil
  - nolintlint
  - perfsprint
  - prealloc
  - predeclared
  - reassign
  - revive
  - staticcheck
  - tagliatelle
  - testableexamples
  - thelper
  - tparallel
  - unconvert
  - unparam
  - unused
  - usestdlibvars
  - wastedassign
  - whitespace

  settings:
    cyclop:
      max-complexity: 30
      package-average: 10.0
    gocognit:
      min-complexity: 20
    gocritic:
      enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
      settings:
        captLocal:
          paramsOnly: false
    govet:
      enable-all: true
      disable:
      - fieldalignment
      settings:
        shadow:
          strict: true
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
      - io/ioutil.ReadFile
      - io.Copy(*bytes.Buffer)
      - io.Copy(os.Stdout)
    nakedret:
      max-func-lines: 1
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
    funlen:
      lines: 100
      statements: 50
      ignore-comments: true
    gochecksumtype:
      default-signifies-exhaustive: false
    inamedparam:
      skip-single-param: true
    mnd:
      ignored-functions:
      - args.Error
      - flag.Arg
      - flag.Duration.*
      - flag.Float.*
      - flag.Int.*
      - flag.Uint.*
      - os.Chmod
      - os.Mkdir.*
      - os.OpenFile
      - os.WriteFile
    nolintlint:
      allow-no-explanation: [ funlen, gocognit, lll ]
      require-explanation: true
      require-specific: true

issues:
  max-same-issues: 50
