version: "2"

run:
  timeout: 5m
  skip-files:
  - ".*\\.my\\.go$"
  - lib/bad.go

linters:
  enable:
  - bodyclose
  - dogsled
  - dupl
  - errcheck
  - funlen
  - gochecknoinits
  - goconst
  - gocritic
  - gocyclo
  - revive
  - mnd
  - goprintffuncname
  - gosec
  - govet
  - ineffassign
  - lll
  - misspell
  - nakedret
  - rowserrcheck
  - copyloopvar
  - staticcheck
  - unconvert
  - unparam
  - unused
  - whitespace

linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: UK
  lll:
    line-length: 120
  gocritic:
    enabled-tags:
    - diagnostic
    - experimental
    - opinionated
    - performance
    - style
    disabled-checks:
    - wrapperFunc
    - dupImport
    - ifElseChain
    - octalLiteral
    - whyNoLint
    - singleCaseSwitch
  funlen:
    lines: 100
    statements: 50
  depguard:
    rules:
      main:
        list-mode: lax
        files:
        - $all
        - "!$test"
        allow:
        - $gostd
        - github.com/sm-moshi/dmetrics-go
        - github.com/sm-moshi/dmetrics-go/api/metrics
        - github.com/sm-moshi/dmetrics-go/pkg/metrics/types
        - github.com/sm-moshi/dmetrics-go/internal/cpu
        - github.com/sm-moshi/dmetrics-go/internal/cpu/darwin
        - github.com/sm-moshi/dmetrics-go/internal/power
        - github.com/sm-moshi/dmetrics-go/internal/power/darwin
      tests:
        list-mode: lax
        files:
        - "$test"
        allow:
        - $gostd
        - github.com/sm-moshi/dmetrics-go
        - github.com/sm-moshi/dmetrics-go/...
        - github.com/stretchr/testify/...

issues:
  exclude:
  - path: _test\.go$
    linters:
    - funlen
    - depguard
  - path: examples/
    linters:
    - revive
  max-issues-per-linter: 0
  max-same-issues: 0

severity:
  case-sensitive: false
  default: error
  rules:
  - linters:
    - funlen
    severity: info
